// Data Biodata
const biodata = {
    nama: "salman alfarissi",
    umur: "20",
    alamat: "kp babakan rt 01 rw 09",
    kelas: "ti23j"
};

// Menampilkan data ke dalam HTML
document.getElementById('nama').textContent = biodata.nama;
document.getElementById('umur').textContent = biodata.umur;
document.getElementById('alamat').textContent = biodata.alamat;
document.getElementById('kelas').textContent = biodata.kelas;

